theme: jekyll-theme-hacker

brand: Oldschoolprogrammer
my_grade: 1
my_school: liceum

excerpt_separator: <!--excerpt-->
collections:
  categories:
    output: true
  tags:
    output: true
  posts:
    output: true
# collections_dir: sortownia

# Theme-specific config
show_downloads: false
title: Oldschool Programmer
description: Blog informatyczny
lang: pl-PL

# jekyll-feed
url: https://ankiedos.github.io
author: Antek
feed:
  posts_limit: 5
  excerpt_only: true