theme: jekyll-theme-hacker

collections:
  categories:
    output: true
  tags:
    output: true
  posts:
    output: true
  authors:
    output: true
  layouts:
    output: true
  includes:
    output: true
collections_dir: sortownia
