theme: jekyll-theme-hacker

brand: Oldschoolprogrammer
my_grade: 1
my_school: liceum
collections:
  categories:
    output: true
  tags:
    output: true
  posts:
    output: true
# collections_dir: sortownia

# Theme-specific config
show_downloads: false
title: Oldschool Programmer
description: Blog informatyczny
lang: pl-PL