theme: jekyll-theme-hacker

collections:
  categories:
    output: true
  tags:
    output: true
  posts:
    output: true
# collections_dir: sortownia

# Theme-specific config
show_downloads: false
title: Oldschool Programmer
description: Blog informatyczny
lang: pl_PL